services:

  core-db:
    image: postgres:16
    container_name: core-db

    environment:
      POSTGRES_DB: banking_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: "123"

    volumes:
      - pg-data:/var/lib/postgresql/data

    networks:
      - banking-network

    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres -d banking_db" ]
      interval: 5s
      timeout: 5s
      retries: 10

  account-service:
    build:
      context: .
      dockerfile: Dockerfile

    container_name: account-service

    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://core-db:5432/banking_db
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: "123"

    ports:
      - "8080:8080"

    depends_on:
      core-db:
        condition: service_healthy

    networks:
      - banking-network

  transaction-service:
    build:
      context: ./transaction-service
      dockerfile: Dockerfile

    container_name: transaction-service

    ports:
      - "8081:8081"

    depends_on:
      - account-service

    networks:
      - banking-network

volumes:
  pg-data:

networks:
  banking-network:
    driver: bridge
