name: Cart Service CI

on:
  push:
    paths:
      - 'session_07/exercise_01/**'
  pull_request:
    paths:
      - 'session_07/exercise_01/**'

jobs:
  build:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: session_07/exercise_01

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Java 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Make Gradle executable
        run: chmod +x gradlew

      - name: Build with Gradle
        run: ./gradlew bootJar